# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: a0fb6e2a7e308746b04e18db362891bba633ef45d68b8aa7f5846130d295af2b03e9ab27022b9cd47815b4fd953b29a56329d9d9caf24d83ae2152827c3bb297

test:
  secret_key_base: 0732f6aca4539847ea907cea6555d359e011087c7a1132f23e15584568fcd8c5bf3404dd410306813d5597c07674aea2862024d7aa94950cf2ea4f19afcefcd9

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
